// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using in_Class5.Models.Portfolio;

namespace in_Class5.Migrations
{
    [DbContext(typeof(ProtfolioContext))]
    partial class ProtfolioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("in_Class5.Models.Portfolio.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("in_Class5.Models.Portfolio.Technology", b =>
                {
                    b.Property<string>("Name");

                    b.HasKey("Name");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("in_Class5.Models.Portfolio.TechnologyProjects", b =>
                {
                    b.Property<string>("TechnoglyName");

                    b.Property<int>("ProjectId");

                    b.HasKey("TechnoglyName", "ProjectId");

                    b.HasAlternateKey("ProjectId", "TechnoglyName");

                    b.ToTable("TechnologyProjects");
                });

            modelBuilder.Entity("in_Class5.Models.Portfolio.TechnologyProjects", b =>
                {
                    b.HasOne("in_Class5.Models.Portfolio.Project", "Project")
                        .WithMany("TechnologyProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("in_Class5.Models.Portfolio.Technology", "Technology")
                        .WithMany("TechnologyProjects")
                        .HasForeignKey("TechnoglyName")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
